### ISSUE TITLE
comments on README

### ISSUE THREAD

**Issue by javier-romero** [potassco/fclingo#21]
### 1

* https://github.com/potassco/fclingo/blob/71cd3377deda295441d6922f4d698e04cd7eda21/README.md?plain=1#L13
I think this paragraph is overkill to start with. 
I would write something shorter here, and move part of the explanations somewhere below.
And I would structure the text with subsections, one to explain the relation to clingcon and another to explain the relation to clingo.

### 2
* https://github.com/potassco/fclingo/blob/71cd3377deda295441d6922f4d698e04cd7eda21/README.md?plain=1#L16C3
I would try not to talk about constraints and talk just about atoms. Coming from clingo, the theory atoms are just another type of atoms like aggregate atoms.

### 3

I would rewrite the example like this:
```
price(frame,15).
price(bag,5).

  selected(frame).
{ selected(bag) }.

&sum{V} = price(P) :- selected(P), price(P,V).
&sum{price(P) : selected(P)} = price(total).

#show selected/1.
&show{price/1}.
```
Just simplified the names, and reorder the first rule with &sum so that both rules look the same.

### 4
* https://github.com/potassco/fclingo/blob/71cd3377deda295441d6922f4d698e04cd7eda21/README.md?plain=1#L61
Be careful talking about `undefined variables`: the reader does not know what is a variable (`a` or `A`?) or what is undefined.

### 5
* https://github.com/potassco/fclingo/blob/71cd3377deda295441d6922f4d698e04cd7eda21/README.md?plain=1#L94
Now that we switched the order, we lose the motivation for `sus`. This just shows that the behavior is different, but it does not show what is the point of having `sus` in addition of `sum`. Another variation of the example is needed for that.

### 6
* https://github.com/potassco/fclingo/blob/71cd3377deda295441d6922f4d698e04cd7eda21/README.md?plain=1#L125
This is unrelated, but in the end it would also be nice to allow the `&in` in the body.

**Comment by wanko** [comment]
Done
